apiVersion: v1
kind: Service
metadata:
  name: hw-outer-service
spec:
  selector:
    feeling: ThisWorldIsUnfirendly_nginx
  ports:
    - port: 9010
      name: outer-service-port
      protocol: TCP
      targetPort: 80