apiVersion: v1
kind: Secret
metadata:
  name: secret-file-for-mysql
type: Opaque
data:
  wp_username: d3AtdXNlcg==
  # username for wordPress
  wp_password: aGFuZHNvbmljdmVyMjg=
  # password for wordPress
  root_password: YXk5MDEweA==
  # password for root
