apiVersion: v1
kind: Service
metadata:
  name: hw-wordpress-service
spec:
  selector:
    feeling: ThisWorldIsUnfirendly_wordpress
  ports:
    - port: 8000
      name: wordpress-service-port
      protocol: TCP
      targetPort: 80
