apiVersion: v1
kind: Service
metadata:
  name: hw-mysql-service
spec:
  selector:
    feeling: ThisWorldIsUnfirendly_mysql_StatefulSet
  ports:
    - port: 3306
      name: mysql-service-port
      protocol: TCP
      targetPort: 3306