apiVersion: v1
data:
  t-nginx.conf: "        server {\r\n            listen 80 default_server;\r\n            location
    / {\r\n                # $http_host is the host name that users seen on the browser
    URL\r\n                # and it equals to `HTTP_HOST` request header.\r\n                proxy_set_header
    Host $http_host;\r\n\r\n                proxy_pass http://hw-wordpress-service:8000;\r\n\r\n
    \               # Modify `Location` of 301 or 302 HTTP response, so\r\n                #
    that the browser will follow the correct location.\r\n                # proxy_redirect
    ~^http://[^/]*/(.*) http://$http_host/$1;\r\n            }\r\n        }"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-04T03:51:13Z"
  name: hw-nginx-configmap
  ##namespace: hwtest
  resourceVersion: "248074"
  uid: 5f5f37be-41c7-46bc-9eeb-fe9478d2f37f
